# Generated by Django 4.0.3 on 2022-03-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='sensor',
            field=models.ManyToManyField(related_name='sensor', to='measurement.sensor'),
        ),
    ]
