# Generated by Django 4.0.3 on 2022-03-20 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_alter_measurement_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='sensor',
        ),
    ]
