# Generated by Django 4.0.3 on 2022-03-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_remove_measurement_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='sensor',
            field=models.ManyToManyField(related_name='sensor', to='measurement.sensor'),
        ),
    ]
